<?php
echo " <table width=\"90%\" border=\"0\" bgcolor=\"$tabla\" cellpadding=\"1\" cellspacing=\"1\">";
echo "   <tr>";
echo "     <th colspan=\"2\" scope=\"col\">ENERO</th>";
echo "     <th colspan=\"2\" scope=\"col\">FEBRERO</th>";
echo "     <th colspan=\"2\" scope=\"col\">MARZO</th>";
echo "     <th colspan=\"2\" scope=\"col\">ABRIL</th>";
echo "     <th colspan=\"2\" scope=\"col\">MAYO</th>";
echo "     <th colspan=\"2\" scope=\"col\">JUNIO</th>";
echo "     <th colspan=\"2\" scope=\"col\">JULIO</th>";
echo "     <th colspan=\"2\" scope=\"col\">AGOSTO</th>";
echo "     <th colspan=\"2\" scope=\"col\">SEPTIEMBRE</th>";
echo "     <th colspan=\"2\" scope=\"col\">OCTUBRE</th>";
echo "     <th colspan=\"2\" scope=\"col\">NOVIEMBRE</th>";
echo "     <th colspan=\"2\" scope=\"col\">DICIEMBRE</th>";
echo "     <th colspan=\"2\" scope=\"col\">TOTAL</th>";
echo "   </tr>";
echo "   <tr>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">DH</td>";
echo "     <td bgcolor=\"$celda\" align=\"center\">NDH</td>";
echo "   </tr>";
echo "   <tr>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh1\" name=\"dh1\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh1\" name=\"ndh1\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh2\" name=\"dh2\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh2\" name=\"ndh2\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh3\" name=\"dh3\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh3\" name=\"ndh3\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh4\" name=\"dh4\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh4\" name=\"ndh4\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh5\" name=\"dh5\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh5\" name=\"ndh5\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh6\" name=\"dh6\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh6\" name=\"ndh6\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh7\" name=\"dh7\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh7\" name=\"ndh7\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh8\" name=\"dh8\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh8\" name=\"ndh8\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh9\" name=\"dh9\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh9\" name=\"ndh9\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh10\" name=\"dh10\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh10\" name=\"ndh10\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh11\" name=\"dh11\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh11\" name=\"ndh11\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dh12\" name=\"dh12\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndh12\" name=\"ndh12\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"dht\" name=\"dht\" min=\"10\" max=\"100\" required></td>";
echo "     <td bgcolor=\"$celda\" align=\"center\"><input type=\"number\" id=\"ndht\" name=\"ndht\" min=\"10\" max=\"100\" required></td>";
echo "   </tr>";
echo " </table>";
?>